version: "3.9"

services:
  web:
    build: ./app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: embrass
      POSTGRES_PASSWORD: StrongPass123
      POSTGRES_DB: tg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
